# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='items',
            field=models.ManyToManyField(to='menu.Item'),
        ),
    ]
