# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180419_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='menu.Ingredient'),
        ),
    ]
