# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180419_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='menu.ItemIngredient', to='menu.Ingredient'),
        ),
        migrations.AddField(
            model_name='itemingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Item'),
        ),
    ]
