# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180419_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='itemingredient',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='menu.Ingredient'),
        ),
        migrations.DeleteModel(
            name='ItemIngredient',
        ),
    ]
